### PR TITLE
ui adjust in mifosx317

### PR DESCRIPTION
**Pull request by wuyanna**
ui adjust in mifosx317

"It would probably be easier for a user, if we had an icon (say a question mark) in front of the fields and have the tooltip associated with this icon (rather than the label).

We also wouldn't mind some pretty tooltips like http://jqueryui.com/tooltip/#custom-style"

### CODE REVIEW

**Comment by vishwasbabu** [comment]
Many Thanks Yanna!

The tooltip looks perfect.

The JQuery upgrade is causing a few issues though (Navigate to a client with a couple of loans-> Click on a loan -> Now all tabs appear buggy)

This is most probably because of some JQuery version specific scripting we had done for opening new tabs (opening an existing tab based on ID etc).

I will take a more detailed look at the JQuery version issue a bit later.

**Comment by vishwasbabu** [comment]
Yanna,

Do you happen to have the code for this pull request (ui adjust in mifosx317) in a local branch? If so could you send across another pull request?

**Comment by wuyanna** [comment]
It seems that I lost the code. My bad, I should have created a branch. Don't worry, I can fix this very quickly.

**Comment by wuyanna** [comment]
Send another pull request, close this one

**Pull request closed without merging**
