### PR TITLE
MIFOSX-282: restrict change of interest rate period in new/modify loan

### PR DESCRIPTION
**Pull request by ashokauty**
Hi Keith,

Added restriction to change of Interest rate period in new /modify loan.

Regards
Ashok

### CODE REVIEW

**Comment by keithwoodlock** [comment]
Ashok,

When submitting new loan application I get the following validation error:

Interest rate frequency period type is mandatory.

So you need to add a hidden field to pass the interestRatePeriodFrequencyType parameter with value from loan product.

**Comment by keithwoodlock** [comment]
Actually, forgot what i said here. added comments to issue https://mifosforge.jira.com/browse/MIFOSX-282

**Comment by ashokauty** [comment]
Hi Keith,

Did you try using latest MIFOSX-282 UI code changes? I added a code snippet
to fetch interestRatePeriodFrequencyTyp and send it to API.

Regards

Ashok

**Comment by keithwoodlock** [comment]
Ashok, I probably did forget to refresh my browswer to pick up on new changes but as said in issue, you can scrap my first comment cause this should not allowed - The API should not support the parameter and allow someone to change this value through API.

**Comment by ashokauty** [comment]
Hi Keith,

I am working on this change, I am assuming that we still persist the
interestRatePeriodFrequencyTyp in m_loan table, instead of getting it from
UI it should be copied from loan product.

Regards
Ashok

**Comment by keithwoodlock** [comment]
Thanks ashok, 

Yes its ok to leave it be peristed on m_loan table as it is currently.

**Pull request merged**
