### PR TITLE
webcam integration

### PR DESCRIPTION
**Pull request by vishwasbabu**
Keith,

For running the same locally, we would need to trust the file system folder from which SWF file is loaded in Flash Player global settings. 

1) Right click on flash player 
2) Select Global settings
3) Select advanced tab
4) Scroll down and select "Trusted location settings"
5) Click add and browser to the Individual lending Javascript folder and click add
6) You would need to re-load the flash player again for the settings to take affect (refresh the screen)

### CODE REVIEW

**Comment by keithwoodlock** [comment]
Vishwas, I brought this in but I could not get it to work for me

When i click the camera icon, dialog loads and I get asked if i want to allow access to camera and microphone which i do. When i click capture however it simply goes to the following url file:///C:/dev/mifosx-community-apps/IndividualLendingGeneralJavaScript/IndivLendHome.html#

which makes app go back to login page.

**Comment by vishwasbabu** [comment]
Keith,

This is due to restrictions Flash player places on locally loaded SWF files.

You would have to do the things listed in the last comment of https://mifosforge.jira.com/browse/MIFOSX-78 for overcoming the same

Thanks and Regards,
Vishwas

**Comment by keithwoodlock** [comment]
Vishwas,

Thanks. seems i've turned into one of those people who dont read the manual :)

It works very well. Very cute.

So for someone to use this feature on the demo server how would it work?

**Comment by johnw65** [comment]
maybe the server isn't local :)

**Comment by vishwasbabu** [comment]
> > maybe the server isn't local :)

Yes. I am hoping it works without any issues

The last Build on the production server has some issues in image Management (Data URL’s weren’t being parsed properly for some reason).

Will check if the same persists after deploying a newer Build

Cheers,

Vishwas

+91-9986077286

**Pull request merged**
