### PR TITLE
Reuse of loans API for bulk creation of group members loans.

### PR DESCRIPTION
**Pull request by mdudzinski**
Possibility to create multiple group members loan accounts.
Next step will be screen with members accounts listing with basic operations => approve, delete, disburse.

I will be happy to hear any opinions/thoughts/suggestions.

Thanks in advance.

### CODE REVIEW

**Comment by keithwoodlock** [comment]
Michal,

Thanks for the pull-request. I can see now a ui to demostrate abliity to create loans for each member of the group.

As you have said, nexts steps are the ability to show these loans against the members in the group interface and allow people to perform actions against the loan.

One thing that does seem to be missing is that when you 'create' the loan applications against the client (the group) is not tracked on the backend - so client_id is populated but not the group_id - would expect we might need both to be populated so we can determine that a given loan application was driven from the 'group' interface.

I might be wrong though. What do you think?

**Comment by mdudzinski** [comment]
Keith,

saying populating group_id do you mean persist it in m_loan table (so client_id and group_id will not be null) or just return both in json response?

Anyway, after some thought I think that group_id should be tracked if loan was driven from 'group' context because currently there is possibility to have client in more than one group. Do you agree?

**Comment by keithwoodlock** [comment]
Michal,

Yes thats exactly what I am talking about. When creating loans from group context - makes sense to track the group_id along with client_id in the m_loan table.

Just for fetching the correct data to bring back you would need to know what loans are associated with group context (along with client information)

Some MFIs may have constraints around restricting number of groups a client can belong to etc or number of loans a client can have out at same time (from group or individually) and some wont have constraints around this so this type of business rule validation is something we would get to later with input from MFIs.

**Comment by mdudzinski** [comment]
Okay, so I will prepare little update to mifos x platform to add support for group_id tracking.

**Pull request merged**
