### PR TITLE
Adding document management facilities for loans

### PR DESCRIPTION
**Pull request by vishwasbabu**
Keith, 

There is a known issue with this commit:

When a user opens the same loan in two separate jquery tabs (by clicking on the loan link twice in user summary tab) the document management tab would work only for the first tab 

However it does work as expected when multiple loan products are opened in separate jquery tabs etc.

I was thinking instead of fixing this issue, would it be better if  I raised a separate bug on Jira and not allow opening multiple loan tabs for the same loan when a user clicks on them in the summary tab (simply refresh the existing tab instead)

What would you advise?

### CODE REVIEW

**Comment by keithwoodlock** [comment]
Vishwas,

your right. When we click a loan link to view loan details - if the loan is not already open should open up new tab, if it is already open, the user should be switched into that tab rather than always opening up new tab.

There is an outstanding issue created for this very scenario already: https://mifosforge.jira.com/browse/MIFOSX-50

Right now no time has been invested in solving this as of yet though. Do you think its something we should try to get right (even for demo stages)

**Comment by vishwasbabu** [comment]
Keith,

Shall I take this up now?

The document management stuff is quite done for now. I’ll get back to Amazon S3 appender and adding more advanced validations for Filetypes allowed etc later.

Cheers,

Vishwas

+91-9986077286

**Comment by keithwoodlock** [comment]
Vishwas, yes please do.

**Comment by keithwoodlock** [comment]
Vishwas, thanks. pull-request accepted and closed.

The only observation I had was when we download the document, the basic auth login pops us as we dont seem to be passing basic auth credentials for file download. Its also something we need to sort out for report exports which are also file downloads. So we will tackle this in time.

**Comment by vishwasbabu** [comment]
Oh!

Firefox was appending the authentication header for me! (Maybe because I
would access a service with rest client every time I restarted the
services..) 

Currently, file download is done using an Iframe (jquery.FileDownload.js
makes it very easy)so there is no standard way (that I know of) to add
headers to the same

I guess appending username/password to the URL (as a temporary workaround)
Ex https://mifos:password@localhost:8443/mifosng-provider.... Is not an
option. (Or is it?)

Cheers,

Vishwas

+91-9986077286

**Pull request merged**
