### PR TITLE
MIFOSX-346 upgrade to jquery 1.10

### PR DESCRIPTION
**Pull request by wuyanna**
MIFOSX-346 upgrade to jquery 1.10
The tabs api of JQuery UI has been changed a lot. 
Reference: http://jqueryui.com/upgrade-guide/1.10/#tabs

### CODE REVIEW

**Comment by vishwasbabu** [comment]
Thanks Yanna, The pull request looks perfect.

Found a minor issue while testing out the "In development" code (can be seen by appending the query parameter mode=dev)

Click on Administrative Units -> Centers -> Select a Center. The tabs under this center have also needs to be updated (The issue here seems to be with the "add" method used which also seems to have been deprecated)

$newtabs = $("#groupdatatabs").tabs({
        beforeActivate: function(event, tab) {
            if (tab.newTab.index() == 0){
                if (groupDirty == true){
                    refreshGroupLoanSummaryInfo(groupUrl);
                    groupDirty = false;
                }
            }
        },
        "add": function( event, ui ) {
                $newtabs.tabs("option", "active", '#' + ui.panel.id);
            }
});

http://stackoverflow.com/questions/14702631/in-jquery-ui-1-9-how-do-you-create-new-tabs-dynamically

**Comment by wuyanna** [comment]
Vishwas, I fixed the issue you mentioned. It was caused by some typos in my last commit. 
As to the deprecated "add" event of tabs, there are several in the code. I'm not sure about where to put the "add" action, because some of them seem never used. If you find issues when adding tabs, please tell me.

**Comment by vishwasbabu** [comment]
Thanks Yanna.

Sorry for being a bit of an ass :)

The issue I am currently seeing is as follows:

1) Switch to develop mode by adding a query param &mode=dev to the UI
Ex: file:///W:/mifos/mifosx-community-apps/IndividualLendingGeneralJavaScript/IndivLendHome.html?tenantIdentifier=default&baseApiUrl=https://localhost:8443/mifosng-provider/api/v1/&mode=dev#

2) Click on Administrative Units -> Centers

3) Enter Valid details to create a new center (say "Test Center")

4) Tabs "Groups" and  "Summary tab" in the "Test Center" don't seem to work

**Comment by wuyanna** [comment]
Sorry for the mistake, I didn't know what it should look like because I couldn't connect to demo server these days. It seems that the correspondant div should be created in advance, which is also different from the previous version of jquery ui. Please test again.

**Comment by vishwasbabu** [comment]
Perfect Yanna! Very happy to accept this pull request :)

**Pull request closed without merging**
